plugins {
}

    android {
    namespace 'com.morechili.googlesignproject'
    compileSdk 35

    defaultConfig {
      applicationId "com.morechili.googlesignproject"
    minSdk 24
    targetSdk 35
    versionCode 1
    versionName "1.0"

      testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
       release {
           minifyEnabled false
           proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
       }
    }
    }

  dependencies {

  }